/******************************************************************************
 * @file    TicTacToe.c
 * @author  Generated by AI Assistant
 * @date    2025-10-28
 ******************************************************************************
 * Description:
 *   井字棋游戏模块，包含游戏的主要逻辑实现
 *
 * Functions:
 *   - ttt_init_game() : 初始化游戏
 *   - ttt_run_game()  : 运行游戏主循环
 *   - 其他辅助函数用于游戏逻辑处理
 ******************************************************************************
 * @version 1.0
 ******************************************************************************/

/*=============================================================================
 *                           头文件包含区
 *===========================================================================*/

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include "Tprint.h"
#include "GamesAi.h"
#include "TicTacToe.h"

/*=============================================================================
 *                          宏定义区
 *===========================================================================*/

#define BOARD_SIZE 3

/*=============================================================================
 *                          类型定义区
 *===========================================================================*/

/*=============================================================================
 *                          全局变量区
 *===========================================================================*/

static char gameBoard[BOARD_SIZE][BOARD_SIZE];

/*=============================================================================
 *                          函数声明区
 *===========================================================================*/

static void initBoard(char board[BOARD_SIZE][BOARD_SIZE]);
static void printBoard(char board[BOARD_SIZE][BOARD_SIZE]);
static int isValidMove(char board[BOARD_SIZE][BOARD_SIZE], int row, int col);
static int makeMove(char board[BOARD_SIZE][BOARD_SIZE], int row, int col, char player);
static int checkWin(char board[BOARD_SIZE][BOARD_SIZE], char player);
static int isBoardFull(char board[BOARD_SIZE][BOARD_SIZE]);
static void getPlayerMove(char board[BOARD_SIZE][BOARD_SIZE], char player);
static void playGame(void);

/*=============================================================================
 *                          函数实现区
 *===========================================================================*/

/**
 * 初始化游戏
 */
void ttt_init_game(void)
{
    // 初始化游戏相关资源
}

/**
 * 运行游戏主循环
 */
void ttt_run_game(void)
{
    int playAgain;
    
    do {
        playGame();
        printf("是否再玩一次? (1=是, 0=否): ");
        scanf("%d", &playAgain);
    } while (playAgain == 1);
    
    printf("感谢游玩!\n");
}

/**
 * 初始化棋盘
 */
static void initBoard(char board[BOARD_SIZE][BOARD_SIZE])
{
    for (int i = 0; i < BOARD_SIZE; i++) 
    {
        for (int j = 0; j < BOARD_SIZE; j++) 
        {
            board[i][j] = ' ';
        }
    }
}

/**
 * 打印棋盘
 */
static void printBoard(char board[BOARD_SIZE][BOARD_SIZE])
{
    printf("\n");
    printf(" %c | %c | %c \n", board[0][0], board[0][1], board[0][2]);
    printf("---|---|---\n");
    printf(" %c | %c | %c \n", board[1][0], board[1][1], board[1][2]);
    printf("---|---|---\n");
    printf(" %c | %c | %c \n", board[2][0], board[2][1], board[2][2]);
    printf("\n");
}

/**
 * 检查移动是否有效
 */
static int isValidMove(char board[BOARD_SIZE][BOARD_SIZE], int row, int col)
{
    if (row < 0 || row >= BOARD_SIZE || col < 0 || col >= BOARD_SIZE) 
    {
        return 0;
    }
    return board[row][col] == ' ';
}

/**
 * 在指定位置放置棋子
 */
static int makeMove(char board[BOARD_SIZE][BOARD_SIZE], int row, int col, char player)
{
    if (isValidMove(board, row, col)) 
    {
        board[row][col] = player;
        return 1;
    }
    return 0;
}

/**
 * 检查玩家是否获胜
 */
static int checkWin(char board[BOARD_SIZE][BOARD_SIZE], char player)
{
    // 检查行
    for (int i = 0; i < BOARD_SIZE; i++) 
    {
        if (board[i][0] == player && board[i][1] == player && board[i][2] == player) 
        {
            return 1;
        }
    }
    
    // 检查列
    for (int j = 0; j < BOARD_SIZE; j++) 
    {
        if (board[0][j] == player && board[1][j] == player && board[2][j] == player) 
        {
            return 1;
        }
    }
    
    // 检查对角线
    if (board[0][0] == player && board[1][1] == player && board[2][2] == player) 
    {
        return 1;
    }
    if (board[0][2] == player && board[1][1] == player && board[2][0] == player) 
    {
        return 1;
    }
    
    return 0;
}

/**
 * 检查棋盘是否已满
 */
static int isBoardFull(char board[BOARD_SIZE][BOARD_SIZE])
{
    for (int i = 0; i < BOARD_SIZE; i++) 
    {
        for (int j = 0; j < BOARD_SIZE; j++) 
        {
            if (board[i][j] == ' ') 
            {
                return 0;
            }
        }
    }
    return 1;
}

/**
 * 获取玩家的移动
 */
static void getPlayerMove(char board[BOARD_SIZE][BOARD_SIZE], char player)
{
    int row, col;
    printf("玩家 %c, 请输入您的移动 (行 列): ", player);
    scanf("%d %d", &row, &col);
    
    // 转换为0索引
    row--;
    col--;
    
    if (!makeMove(board, row, col, player)) 
    {
        printf("无效移动! 请重试。\n");
        getPlayerMove(board, player);
    }
}

/**
 * 主游戏循环
 */
static void playGame(void)
{
    char board[BOARD_SIZE][BOARD_SIZE];
    char currentPlayer = 'X';
    int gameMode;
    
    printf("欢迎来到井字棋游戏!\n");
    printf("请选择游戏模式:\n");
    printf("1. 双人游戏\n");
    printf("2. 与AI对战\n");
    printf("请输入选择 (1 或 2): ");
    scanf("%d", &gameMode);
    
    initBoard(board);
    
    while (1) 
    {
        printBoard(board);
        
        if (gameMode == 1) 
        {
            // 双人游戏
            getPlayerMove(board, currentPlayer);
        } 
        else if (gameMode == 2) 
        {
            // 与AI对战
            if (currentPlayer == 'X') 
            {
                // 玩家回合
                getPlayerMove(board, currentPlayer);
            } 
            else 
            {
                // AI回合
                printf("AI 正在思考...\n");
                aiMakeMove(board, currentPlayer);
            }
        }
        
        // 检查当前玩家是否获胜
        if (checkWin(board, currentPlayer)) 
        {
            printBoard(board);
            if (gameMode == 2 && currentPlayer == 'O') 
            {
                printf("AI 获胜!\n");
            } 
            else 
            {
                printf("玩家 %c 获胜!\n", currentPlayer);
            }
            break;
        }
        
        // 检查是否平局
        if (isBoardFull(board)) 
        {
            printBoard(board);
            printf("平局!\n");
            break;
        }
        
        // 切换玩家
        currentPlayer = (currentPlayer == 'X') ? 'O' : 'X';
    }
}